import Link from "next/link";
import { DashboardShell } from "@/components/dashboard-shell";
import { pullRequestTrace, teamWorkspace } from "@/lib/agenttraces-api";
import { ProviderLabel } from "@/components/provider-icon";

export default async function PullRequestPage({ params, searchParams }: { params: Promise<{ number: string }>; searchParams: Promise<{ repository?: string }> }) {
  const [{ number }, query] = await Promise.all([params, searchParams]); const repository = query.repository ?? "OximyHQ/agenttraces";
  const [data, team] = await Promise.all([pullRequestTrace(repository, Number(number)), teamWorkspace()]); const pr = data.pullRequest;
  if (!pr) return <DashboardShell section="pull-requests" workspaceName={team.workspace?.name ?? "Personal"} deviceCount={team.workspace?.deviceCount ?? 0}><Link className="back-link" href="/dashboard/pull-requests">← Pull requests</Link><div className="query-panel"><h1>Pull request not found</h1><p>No accessible trace is linked to {repository} #{number}.</p></div></DashboardShell>;
  const title = String(pr.title ?? "Pull request"); const state = String(pr.state ?? "unknown"); const repo = String(pr.repository ?? repository); const tokens = data.usage.inputTokens + data.usage.outputTokens; const contributors = new Set(data.traces.map((trace) => trace.owner)).size;
  return <DashboardShell section="pull-requests" preview={data.preview} workspaceName={team.workspace?.name ?? "Personal"} deviceCount={team.workspace?.deviceCount ?? 0}><Link className="back-link" href="/dashboard/pull-requests">← Pull requests</Link><div className="pr-heading"><span className="pr-state">{state === "open" ? "○" : "●"}</span><div><p className="context-line">{repo} · {state}</p><h1>{title} <span>#{number}</span></h1></div></div><dl className="pr-summary"><div><dt>Linked traces</dt><dd>{data.traces.length}</dd></div><div><dt>Contributors</dt><dd>{contributors}</dd></div><div><dt>Tokens</dt><dd>{new Intl.NumberFormat("en", { notation: "compact" }).format(tokens)}</dd></div><div><dt>Cost</dt><dd>{data.usage.accuracy.replaceAll("_", " ")}<small>${data.usage.costUsd.toFixed(2)} reported</small></dd></div></dl><section className="dashboard-section"><h2>Agent work behind this pull request</h2>{data.traces.length ? <div className="pr-traces">{data.traces.map((trace, index) => <Link href={`/dashboard/traces/${trace.id}`} key={trace.id}><span className="trace-sequence">{index + 1}</span><span><strong>{trace.title}</strong><small>{trace.owner} · <ProviderLabel source={trace.source} /> · {trace.duration}</small><em>{String(pr.evidence ?? trace.pullRequests[0]?.evidence ?? "linked")}</em></span><b>{trace.tokens}</b></Link>)}</div> : <p className="page-description">The pull request is known, but no linked trace is accessible to this account.</p>}</section><section className="dashboard-section"><h2>How these were linked</h2><p className="page-description">Exact commits, repository and branch matches, inferred evidence, and manual confirmation remain distinct so the attribution is inspectable.</p></section></DashboardShell>;
}
