import Link from "next/link";
import { DashboardShell } from "@/components/dashboard-shell";
import { teamWorkspace, traces } from "@/lib/agenttraces-api";

export default async function PullRequests() {
  const [data, team] = await Promise.all([traces(), teamWorkspace()]);
  const linked = new Map<string, { number: number; title: string; state: string; repository: string; traceIds: Set<string>; tokens: number }>();
  for (const trace of data.records) for (const pr of trace.pullRequests) { const repository = pr.repository ?? trace.repository; const key = `${repository}#${pr.number}`; const row = linked.get(key) ?? { number: pr.number, title: pr.title, state: pr.state, repository, traceIds: new Set(), tokens: 0 }; if (!row.traceIds.has(trace.id)) { row.traceIds.add(trace.id); row.tokens += Number(trace.tokens.replace(/[^0-9.]/g, "")) * (trace.tokens.toLowerCase().includes("m") ? 1_000_000 : trace.tokens.toLowerCase().includes("k") ? 1_000 : 1); } linked.set(key, row); }
  return <DashboardShell section="pull-requests" preview={data.preview} workspaceName={team.workspace?.name ?? "Personal"} deviceCount={team.workspace?.deviceCount ?? 0}><div className="page-heading"><div><p className="context-line">GitHub</p><h1>Pull requests and their agent work</h1></div><Link className="text-action" href="/docs/github">Configure GitHub App</Link></div><p className="page-description">Open a pull request to see every linked coding session, why it was linked, and the aggregate reported usage.</p>{linked.size ? <div className="pr-list">{[...linked.values()].map((pr) => <Link href={`/dashboard/pull-requests/${pr.number}?repository=${encodeURIComponent(pr.repository)}`} key={`${pr.repository}#${pr.number}`}><span className="pr-state">{pr.state === "open" ? "○" : "●"}</span><span><strong>#{pr.number} {pr.title}</strong><small>{pr.repository} · {pr.traceIds.size} linked trace{pr.traceIds.size === 1 ? "" : "s"}</small></span><span className="pr-usage">{new Intl.NumberFormat("en", { notation: "compact" }).format(pr.tokens)}<small>tokens</small></span><b>→</b></Link>)}</div> : <div className="query-panel"><p>No accessible traces are linked to a pull request yet. Install the read-only GitHub App and connect its installation to your team.</p><code>agenttraces github connect --team TEAM_ID --installation INSTALLATION_ID --account your-org</code></div>}</DashboardShell>;
}
