"use client";

import { useState } from "react";
import { authClient } from "@/lib/auth-client";

export function SignInForm() {
  const [mode, setMode] = useState<"sign-in" | "sign-up">("sign-in"); const [state, setState] = useState<"idle" | "loading" | "error">("idle"); const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setState("loading"); const data = new FormData(event.currentTarget); const email = String(data.get("email")); const password = String(data.get("password")); const name = String(data.get("name") || email.split("@")[0]); const result = mode === "sign-up" ? await authClient.signUp.email({ email, password, name, callbackURL: "/dashboard" }) : await authClient.signIn.email({ email, password, callbackURL: "/dashboard" }); if (result.error) { setMessage(result.error.message ?? "Sign in failed. Check your details and try again."); setState("error"); } else window.location.assign("/dashboard"); }
  async function github() { setState("loading"); const result = await authClient.signIn.social({ provider: "github", callbackURL: "/dashboard" }); if (result.error) { setMessage("GitHub sign-in is not configured for this deployment."); setState("error"); } }
  return <div className="auth-form"><button className="github-button" type="button" onClick={github} disabled={state === "loading"}><span aria-hidden="true">◉</span> Continue with GitHub</button><div className="form-divider"><span>or use email</span></div><form onSubmit={submit}>{mode === "sign-up" && <label>Name<input name="name" autoComplete="name" required /></label>}<label>Email<input name="email" type="email" autoComplete="email" required /></label><label>Password<input name="password" type="password" minLength={10} autoComplete={mode === "sign-up" ? "new-password" : "current-password"} required /></label>{state === "error" && <p className="form-error" role="alert">{message}</p>}<button className="primary-button" type="submit" disabled={state === "loading"}>{state === "loading" ? "Working…" : mode === "sign-in" ? "Sign in" : "Create account"}</button></form><button className="switch-auth" type="button" onClick={() => { setMode(mode === "sign-in" ? "sign-up" : "sign-in"); setState("idle"); }}>{mode === "sign-in" ? "New to AgentTraces? Create an account" : "Already have an account? Sign in"}</button></div>;
}
