import Link from "next/link";
import { DashboardShell } from "@/components/dashboard-shell";
import { teamWorkspace } from "@/lib/agenttraces-api";

function text(row: Record<string, unknown>, key: string, fallback = "—") { return row[key] == null ? fallback : String(row[key]); }
function when(value: unknown) { return value ? new Date(String(value)).toLocaleString() : "Never seen"; }

export default async function TeamPage() {
  const data = await teamWorkspace(); const team = data.workspace;
  if (!team) return <DashboardShell section="team" workspaceName="Personal" deviceCount={0}><div className="page-heading"><div><p className="context-line">Personal workspace</p><h1>Team and devices</h1></div><Link className="text-action" href="/docs/teams">Team guide</Link></div><section className="dashboard-section"><div className="query-panel"><h2>Create your first team</h2><p>The owner sets the default visibility, registers repositories, and creates bounded setup links for teammates.</p><code>agenttraces team create platform --visibility private</code></div></section></DashboardShell>;
  return <DashboardShell section="team" preview={data.preview} workspaceName={team.name} deviceCount={team.deviceCount}>
    <div className="page-heading"><div><p className="context-line">{team.name}</p><h1>Team and devices</h1></div><Link className="text-action" href="/docs/teams">Create setup link →</Link></div>
    <div className="team-policy"><div><h2>Capture policy</h2><p>The owner decides the default for team work. Members can always choose stricter privacy.</p></div><strong>{team.visibility === "team" ? "Team-visible by default" : "Private by default"}</strong></div>
    <section className="dashboard-section"><div className="section-heading"><h2>Registered devices</h2><span>{team.devices.length} devices</span></div>{team.devices.length ? <div className="member-table" role="table" aria-label="Team devices">{team.devices.map((device, index) => { const name = text(device, "principal_name", text(device, "name", "Team member")); return <div role="row" key={text(device, "id", text(device, "email", String(index)))}><span className="member-avatar" aria-hidden="true">{name[0]?.toUpperCase()}</span><span role="cell"><strong>{name}</strong><small>{text(device, "email", "No email reported")}</small></span><span role="cell">{text(device, "role")}</span><span role="cell"><strong>{text(device, "name", "Unnamed device")}</strong><small>{when(device.last_seen_at)}</small></span><span aria-label="Registered device">✓</span></div>; })}</div> : <div className="query-panel"><p>No team devices have registered yet.</p><code>agenttraces team setup-link create {team.id ?? "TEAM_ID"} --domain example.com</code></div>}</section>
    <section className="dashboard-section"><div className="section-heading"><h2>Team repositories</h2><Link href="/docs/teams">Add repository →</Link></div><p className="page-description">Owners and admins may inspect private traces only when the trace belongs to a repository listed here.</p>{team.repositories.length ? <div className="repository-list">{team.repositories.map((item) => { const repository = text(item, "repository"); return <div key={repository}><span aria-hidden="true">◇</span><strong>{repository}</strong><small>GitHub · team-owned</small></div>; })}</div> : <div className="query-panel"><code>agenttraces team repository add {team.id ?? "TEAM_ID"} https://github.com/org/repo</code></div>}</section>
    <section className="dashboard-section"><div className="section-heading"><h2>Setup links</h2><span>{team.setupLinks.length} created</span></div>{team.setupLinks.length ? <div className="repository-list">{team.setupLinks.map((item) => <div key={text(item, "id")}><span aria-hidden="true">↗</span><strong>{text(item, "email", text(item, "domain", "Reusable team link"))}</strong><small>{text(item, "uses_count", "0")} / {text(item, "max_uses")} uses · expires {when(item.expires_at)}</small></div>)}</div> : <div className="query-panel"><p>The raw join URL is shown only when created; the dashboard stores its bounded metadata.</p><code>agenttraces team setup-link create {team.id ?? "TEAM_ID"} --email teammate@example.com</code></div>}</section>
  </DashboardShell>;
}
