import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteFooter, SiteHeader } from "@/components/site-header";
import { ProviderLabel } from "@/components/provider-icon";

const pages: Record<string, { title: string; intro: string; blocks: Array<{ heading: string; body: string; command?: string }> }> = {
  quickstart: { title: "Quickstart", intro: "Capture new sessions locally, verify the installation, then claim the device when you want cloud history.", blocks: [{ heading: "Install", body: "The installer detects supported native stores, explains capture, encrypts the durable local spool, and adds the MCP server to supported clients.", command: "npx agenttraces up" }, { heading: "Verify", body: "Doctor checks the database, all seven parsers, local source detection, Git context, and private key permissions.", command: "npx agenttraces doctor --json" }, { heading: "Find earlier work", body: "Search phrases, repositories, and sources. Add --local when you explicitly want only the machine cache.", command: "agenttraces search \"queue timeout\" --json" }] },
  sources: { title: "Supported agents", intro: "AgentTraces reads native local artifacts and keeps the originating agent and model attached to every normalized event.", blocks: [{ heading: "Current parser coverage", body: "Claude Code, Codex, Cursor, OpenClaw, Conductor, Antigravity, and GitHub Copilot are included. Provider marks are visual shortcuts; the written source name remains authoritative and accessible." }, { heading: "Inspect this machine", body: "Detection is read-only and reports the native stores found without uploading them.", command: "agenttraces doctor --json" }, { heading: "Add another source", body: "A source definition declares bounded paths and SQLite queries; a parser converts native records into stable semantic events without changing the trace contract." }] },
  teams: { title: "Teams and devices", intro: "The owner chooses the team default. Members can always make their own capture stricter.", blocks: [{ heading: "Create the team", body: "A new team starts private unless its owner deliberately chooses team-visible traces.", command: "agenttraces team create platform --visibility private" }, { heading: "Create a setup link", body: "Links can be bound to an email or domain, expire, enforce a usage limit, and be revoked.", command: "agenttraces team setup-link create TEAM_ID --domain example.com" }, { heading: "Register repositories", body: "Team owners and admins may read private traces only for repositories explicitly owned by the team.", command: "agenttraces team repository add TEAM_ID https://github.com/org/repo" }] },
  search: { title: "Search and MCP", intro: "Permission filtering happens before ranking. Results are bounded and retain source provenance.", blocks: [{ heading: "Search from CLI", body: "Use the words you remember; exact session identifiers are optional.", command: "agenttraces search \"authentication regression\"" }, { heading: "Ask through MCP", body: "Use search_traces first, then get_trace with the smallest useful view. find_related_work is intended for proactive retrieval by an agent." }, { heading: "Generate the summary locally", body: "prepare_trace_enrichment returns a bounded excerpt. The active coding agent writes the summary and saves it with save_trace_enrichment." }] },
  "pull-requests": { title: "Traces and pull requests", intro: "A pull request can have many traces; a trace can contribute to more than one pull request.", blocks: [{ heading: "Link evidence", body: "Exact commits, explicit markers, branch and repository matches, time and file overlap, and manual confirmation remain distinguishable." }, { heading: "Inspect a pull request", body: "The result includes each accessible trace plus aggregate tokens, cost, and cost accuracy.", command: "agenttraces pr show --repository https://github.com/org/repo --number 42" }, { heading: "Cost accuracy", body: "Exact, estimated, subscription-included, and unavailable are separate states. AgentTraces never turns a missing price into zero." }] },
  github: { title: "GitHub App", intro: "The public, read-only AgentTraces GitHub App supplies pull-request and push metadata without write access to source code.", blocks: [{ heading: "Install the app", body: "Open https://github.com/apps/agenttraces and choose the repositories AgentTraces may inspect. The app requests read-only code, metadata, and pull-request permissions." }, { heading: "Connect the installation", body: "An owner or admin binds the installation to a team. The cloud stores the installation ID and declared read permissions.", command: "agenttraces github connect --team TEAM_ID --installation 12345 --account your-org" }, { heading: "Automatic attribution", body: "Signed pull_request webhooks upsert repository and PR records. Exact commit matches link at confidence 1; repository and branch matches remain inferred at confidence 0.8 until confirmed." }] },
  sharing: { title: "Sharing", intro: "External shares are immutable snapshots by default, so later trace changes do not silently alter what you published.", blocks: [{ heading: "Choose the surface", body: "Share an overview, conversation, selected highlights, or the full trace. Overview is the safest default." }, { heading: "Readable, bounded links", body: "A public path includes the trace-title slug for recognition and an opaque capability token for access. Choose an audience, expiry, and view limit; every link is revocable and only the token hash is stored." }, { heading: "Opt into live data", body: "Use --live only when viewers should see later changes. This is a deliberate exception to snapshot behavior.", command: "agenttraces share create TRACE_ID --content overview" }] },
  deployment: { title: "Self-hosting", intro: "The open-source stack has separate API, worker, web, and local client processes.", blocks: [{ heading: "Services", body: "Postgres stores normalized records and permissions; Redis queues ingestion; S3-compatible storage preserves compressed native batches." }, { heading: "Authentication", body: "The web app uses Better Auth with GitHub OAuth or email and password. Device tokens remain separate, scoped credentials for CLI ingestion and MCP." }, { heading: "Run verification", body: "The root verification command type-checks every service, runs behavior tests, and exercises every collector parser.", command: "pnpm verify" }] },
};

export default async function DocPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const page = pages[slug]; if (!page) notFound(); return <main><div className="page-frame"><SiteHeader /><article className="doc-page"><Link className="back-link" href="/docs">← Documentation</Link><h1>{page.title}</h1><p className="intro">{page.intro}</p>{slug === "sources" && <div className="source-line source-line-doc"><ProviderLabel source="Claude Code" /><ProviderLabel source="Codex" /><ProviderLabel source="Cursor" /><ProviderLabel source="OpenClaw" /><ProviderLabel source="Conductor" /><ProviderLabel source="Antigravity" /><ProviderLabel source="GitHub Copilot" /></div>}{page.blocks.map((block) => <section key={block.heading}><h2>{block.heading}</h2><p>{block.body}</p>{block.command && <pre><code>{block.command}</code></pre>}</section>)}</article><SiteFooter /></div></main>; }
